import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${font.className} p-3 bg-hexagons dark:bg-hexagons bg-fixed text-slate-900 dark:text-slate-100`}
      >
        <Navbar />
        <div className="min-h-screen max-w-prose mx-auto my-10 md:my-16 px-5 md:px-10">
          {children}
        </div>
      </body>
    </html>
  );
}
